import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import React from 'react';
import ym from 'react-yandex-metrika';
import {YMInitializer} from 'react-yandex-metrika'; 

export default function App({ Component, pageProps, router }: AppProps) {
  // this returns <div id="__next">

  router.events.on('routeChangeComplete', (url: string) => {
    if (typeof (window) !== 'undefined') {
      ym('hit', url);
    }
  });

  return (
      <>
      <Head>
        <title>My Top App - the best Top</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link rel="preconnect" href="https://mc.yandex.ru" />
        <meta property='og:url' content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath} />
        <meta property='og:locale' content='ru_RU' />
      </Head>
      <YMInitializer
        accounts={[]}     
        options={{webvisor: true, defer: true}}
        version='2'
      />
      <Component {...pageProps} />
      </>
  );
}
